/// @file Generated by TurboXML xsdgen. Do not edit by hand.
#pragma once

#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include "TurboXML.hh"

enum class Priority {
  Low,
  Medium,
  High,
};
template <>
struct xml::XmlEnumTraits<Priority> {
  static constexpr auto values = xml::enum_table<Priority>({
      {"Low", Priority::Low},
      {"Medium", Priority::Medium},
      {"High", Priority::High},
  });
};

struct Price;
struct Circle;
struct Square;
struct Order;

struct Price {
  double value{};
  std::string currency{};
};

struct Circle {
  int radius{};
};

struct Square {
  int side{};
};

struct Order {
  int id{};
  Priority priority{};
  Price total{};
  std::optional<xml::DateTime> placed;
  std::vector<std::string> note;
  std::unique_ptr<Order> parent;
  std::vector<std::variant<Circle, Square>> choice;
};

template <>
struct xml::XmlMetadata<Price> {
  static constexpr auto fields = std::make_tuple(
      xml::value_field(&Price::value),
      xml::attr_field("currency", &Price::currency)
  );
};

template <>
struct xml::XmlMetadata<Circle> {
  static constexpr auto fields = std::make_tuple(
      xml::attr_field("radius", &Circle::radius, true)
  );
};

template <>
struct xml::XmlMetadata<Square> {
  static constexpr auto fields = std::make_tuple(
      xml::attr_field("side", &Square::side, true)
  );
};

template <>
struct xml::XmlMetadata<Order> {
  static constexpr auto fields = std::make_tuple(
      xml::attr_field("id", &Order::id, true),
      xml::field("priority", &Order::priority, true),
      xml::field("total", &Order::total, true),
      xml::field("placed", &Order::placed),
      xml::vec_field("note", &Order::note),
      xml::field("parent", &Order::parent),
      xml::variant_field(&Order::choice,
          xml::alt<Circle>("circle"),
          xml::alt<Square>("square"))
  );
};

// root: xml::deserialize(parser, "order", obj);  // Order
